theme: jekyll-theme-midnight

<style>
.tablelines table, .tablelines td, .tablelines th {
        border: 1px solid black;
        }
</style>

.page {
  width: calc(100% - #{$right-sidebar-width-narrow});
}
